/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        Mobile mobile = new Mobile("iPhoneX","White","Apple",0);
        mobile.getBasicInformation();
    }
}
